.gitignore, Makefile, commons/config/config.go, etc/dlaas-service-base/Makefile, lcm/controller/Makefile, metrics/log_collectors/emetrics_file/Makefile, templates/services/trainingdata-deployment.yml, values.yaml
Update configuration files to point to public Docker image repository.
=> Update image repositories

Makefile, README.md, bin/grafana.init.sh
Add minor Makefile support for Clusters that are not Vagrant, Minikube, or IBM Cloud.
=> Add support to none VM_TYPE Clusters

Makefile, etc/examples/caffe-model/lenet_train_test.prototxt
* Fix Caffe Example to pull the datasets from the correct directory.
* Extent make test-submit waiting time.
=> Fix Caffe Example and test-submit waiting time

CONTRIBUTING.md, README.md
Add initial list of contributors. This list is still incomplete and will be extended as we go.
This PR also removes an incorrect reference to a slack channel in `CONTRIBUTING.md`.
=> Add initial list of contributors

README.md, docs/developer-guide.md, lcm/service/lcm/constants.go, lcm/service/lcm/container_helper.go, lcm/service/lcm/container_helper_extensions.go, lcm/service/lcm/resources.go, trainer/trainer/frameworks.go
Add a developer guide docs and move all the development instructions under it. Also added some customizable features in the code base for development build.
* Give instructions to developers for where to modify the codebase for consuming device plugin resources
* Give option in the codebase for developers who want to enable custom learner images for their build. (It also help our development process when adding new frameworks such as horovod)
=> Add developer guide and some customizable features for development build

samples/models.md
=> Compiling a list of Models we can train - expect this to grow

docs/user-guide.md, templates/services/learner-configmap.yml
Add supported framework version for TensorFlow 1.5.1, 1.7.0, and 1.8.0.
person who certified (a), (b) or (c) and I have not …
=> Add latest TensorFlow version support 

etc/examples/tf-model/convolutional_network.py
=> Update tf mnist model to output class probabilities via softmax

community/FfDL-Seldon/tf-model/README.md
=> Fix typo in TFMnist URL link

MAINTAINERS.md
=> Duplicate word on string #15

.helmignore, README.md, community/FfDL-H2Oai/README.md, community/FfDL-H2Oai/h2o-model/manifest-h2o.yml
- Add instructions for H2O's example 
- update Helmignore with new repositories. 
person who certified (a), (b) or (c) and I have …
=> Add instructions for H2O example 

community/FfDL-Seldon/pytorch-model/README.md, community/FfDL-Seldon/tf-model/README.md, demos/fashion-mnist-training/fashion-mnist-webapp/README.md, demos/fashion-mnist-training/fashion-mnist-webapp/fashion-mnist-webapp.yaml, demos/fashion-mnist-training/seldon-deployment/fashion-seldon.json
* Update Fashion MNIST example with Seldon-core 0.2
* Minor docs update to close #112 
person who certified (a), (b) or (c) and I …
=>  Update Fashion MNIST example with Seldon-core 0.2

Chart.yaml, Makefile, etc/examples/tf-model/manifest-for-test.yml, values.yaml
Follow up PR #97 
- Update Helm chart with the new prebuilt images (and update to version v0.1.1)
- Fix some minor bugs with `make test-submit`
Will cut a v0.1.1-rc release after this PR.
(c) …
=> Version control for prebuilt images 

docs/user-guide.md
Markdown: ¿loose on paragraph format?
it.
(d) I understand and agree …
=> Minor proposals on paragraph #57

demos/fashion-mnist-training/fashion-mnist-webapp/static/js/webapp.js
These changes are adopted from https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/blob/master/static/js/webapp.js
https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/pull/22
https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/pull/37
https://github.com/IBM/MAX-Image-Caption-Generator-Web-App/pull/40
by …
=> Fix Firefox file upload error in Fashion demo

etc/converter/train-deploy-wml.md
Update bx command reference to ibmcloud.
Fixed #148 
<br>
it.
(d) I …
=> Update converter bx commands to ibmcloud

demos/fashion-mnist-adversarial/README.md
Fix for https://github.com/IBM/FfDL/issues/155
it.
(d) I understand …
=> Removing references to an internal notebook

docs/detailed-installation-guide.md
The recent PR #158 fixed the bugs that are in the recent versions of DIND. Thus, we need to update the detailed installation instructions on DIND to reflect the same changes.
(c) The …
=> Update detail installation instructions on DIND to reflect the changes in #158

README.md
=> Removing 'latest' reference

LICENSE
Adding name and year per when the file was added.
Signed-off-by: Sahdev Zala <spzala@us.ibm.com>
person who certified (a), (b) or …
=> Add copyright info

demos/fashion-mnist-training/README.md
Adding archive note because pattern will be retired from Developer site
@Tomcli Can you approve/merge?
person who certified (a), …
=> adding archive note
